export EDITOR="nvim"
export PAGER="less"

# miniconda
[ -d $HOME/.local/bin/conda ] && eval "$(/home/asimazbunzel/.local/bin/conda/bin/conda shell.zsh hook)"


# add $HOME/.local/bin to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -not -path "*conda*" -printf %p:)%%:}"

# XDG variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export LESSHISTFILE="-"
