# with interactive, source .zprofile
[ -f $HOME/.zprofile ] &&  source $HOME/.zprofile

# load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"

# path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# zsh theme
ZSH_THEME="robbyrussell"

# plugins
plugins=(git fzf zsh-autosuggestions zsh-syntax-highlighting conda-zsh-completion)

# oh-my-zsh
source $ZSH/oh-my-zsh.sh
