#!/bin/sh

# use neovim for vim if present (from https://github.com/LukeSmithxyz/voidrice/blob/master/.config/aliasrc)
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

alias ls='ls -hN --color=auto --group-directories-first' \
   ll='ls -l' \
   la='ls -A' \
   l='ls -CF'

alias e="$EDITOR" \
   v="$EDITOR" \
   vim="nvim" \
   vimdiff="nvim -d" \
   r="ranger" \
   m="mutt" \
   z="zathura" \
   tn="tmux new -s" \
   tl="tmux ls" \
   ta="tmux attach"

alias df="df -h" \
   grep="grep --color=auto" \
   ssh="ssh -X" \
   ipython="ipython --no-confirm-exit" \
   nano="nano -Sl" \
   bat="bat --wrap=never"

alias plotdig="java -Xmx128m -jar $HOME/.local/bin/plot_digitizer/PlotDigitizer.jar 2>/dev/null"
