#!/bin/sh

# use neovim for vim if present (from https://github.com/LukeSmithxyz/voidrice/blob/master/.config/aliasrc)
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

alias ls='ls -hN --color=auto --group-directories-first' \
   ll='ls -l' \
   la='ls -A' \
   l='ls -CF'

alias e="$EDITOR" \
   v="$EDITOR" \
   vim="nvim" \
   vimdiff="nvim -d" \
   r="ranger" \
   m="mutt" \
   z="zathura"

alias df="df -h" \
   grep="grep --color=auto" \
   ssh="ssh -X" \
   ipython="ipython --no-confirm-exit" \
   free="free -m" \
   cp="cp -i" \
   nano="nano -Sl"

alias plotdig="java -Xmx128m -jar $HOME/.local/bin/plot_digitizer/PlotDigitizer.jar 2>/dev/null"

function cp_to_xrays () {
    scp -r $1 xrays:$2
}

function cp_to_xmm () {
        scp -r $1 xmm-newton:$2
}

colors() {
	local fgc bgc vals seq0

	printf "Color escapes are %s\n" '\e[${value};...;${value}m'
	printf "Values 30..37 are \e[33mforeground colors\e[m\n"
	printf "Values 40..47 are \e[43mbackground colors\e[m\n"
	printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

	# foreground colors
	for fgc in {30..37}; do
		# background colors
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black

			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}

			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
		done
		echo; echo
	done
}

# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
